---
- hosts: all
  become: true
  tasks:
  - debug:
          msg:
          - "ansible_distribution {{ hostvars[inventory_hostname].ansible_distribution }}"
          - "major version {{ hostvars[inventory_hostname].ansible_distribution_major_version }}"
          - "version {{ hostvars[inventory_hostname].ansible_distribution_version }}"

  - name: update repository index
    apt:
     update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package && add php support for apache
    apt:
     name: 
       - apache2
       - libapache2-mod-php
     
     state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update repository index
    yum:
     update_cache: yes
    when: ansible_distribution_version == "RedHat"

  - name: install apache2 package
    yum:
     name:
       - httpd
       - libapache2-mod-php
     state:
       - started
       - latest
    when: ansible_distribution_version == "RedHat"

  